service:
- docker
env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
addons:
  apt:
    update: true
install: true
before_script:
- sudo apt install -y --no-install-recommends bash curl >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
script:
- bash gradlew >/dev/null
- java -jar ./build/libs/*.jar
- bash ./build/libs/*.jar
#
- bash mvnw >/dev/null
- java -jar ./target/*.jar
- bash ./target/*.jar &
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
