spring:
  datasource:
    url: jdbc:h2:file:./spring-jdbc-h2;AUTO_SERVER=TRUE;MULTI_THREADED=TRUE;TRACE_LEVEL_FILE=3;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;AUTO_RECONNECT=TRUE
    username: spring-jdbc-h2
    password: spring-jdbc-h2
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: 'SELECT 1;'
  h2.console.enabled: true
logging.level.org.springframework.jdbc: 'DEBUG'
